language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_palette_picker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: NsdCPk5HLQoUdu1KhmiWFCRBuCkc5rNBcE9NMkFmg2uape3Xj7zbQhQ2AHWS2pgAWbMPj/JsR9IWTSB4ONqKQxOtOHrHtKalHDbMk9bMF8GEckRdNVsfrTZrM0dm0XF9ZqOuGtEc2hOKV2hzi9DZWPuxYEdwgZfvjMKU+6ROw2sgm8eHgt3CRj79ISPEqV/Kbx6Fb8TiDsNrH+ODbbkLKPPSwsve9Idb4jV+uLwGzmKUYRw5EPz1axLy4aaAHndqH+L8p0Mamz6pEEaXoOof+ygMKeuxBhN2pp4PYMXtb7Fr/1zeEnNAxenkCggC78Ni3jPYoYtqNKGZVRjp1YLSixXqfHz3vvqIxolHqaLaREmepw6tsKtX+bzp9FzkwMGI3EuQjkRFZK41H5p5nc3sKPtCW5o/tsveCTU/ROnxmm+3SXq6EFbyEBHLNC8UT0M6ilrY2JDwdE4kQmU3DsrU7vTCgZWdwfV79IolZ5qcMonSRbTcp+qngCXiMoeAn5Uc7o++qsdqypqaxCJmQHObW3HF9eUkhisctj9IHNg5mgQghtpCpZN4i+jn7rjsLXj3gOnbRuKBdwbOVNyMSopplCMwdeRs7h3YYiIEh8ks630ziHZaZN4U9hZv3L3d44F/IQYe5WVLSjqIkYSTg8TQDcDQx1m2fMYiyfIMfu9UZPw=
  app: spenser-palette-picker
  on:
    repo: spenserleighton1/pallete-picker
