language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_palette_picker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: wAECxdhbbYCeF0q2LhwfDaZGNBvJya6PL1Iy9EVq5llkARDvWJXRoKplfo8MBIW5vroGrWlo6ShWBmhcGNecS8kET4XlmaFZx//ttaEOwsTOkbnHAKYP6f9xKKKFZcShW3yZpStS+i9wyRpMs0XsGXirROtxoRmAcnsU53V4qxyt1b3l9iRxajHU0xF7qGOmI7PVctEBCsOg2LGvh7r1Ybkmc9+kd7k+DB9iO2J0e5h8pYo0XPMcVDwcDkN2prReR7yI8TUN68s71HXFpTVt/6JA3Xod0GhvK+yyRMTqYBXBuCVsoRXXqa+8pKeyTJ3LSY8OVVEE0iREQVY1qNU8rxvU7EUrtcSVVmXOSwc02pNtRYlJtMvU2nVUDwoy7qgy6ifQXLHvVbbg7eJdJ4IDBK+CjaMRhLlmnWS6qAPcr1sO6HJKuaTDtO6IKGOKviOl/Uc+oTA6lCEcLb+D832BGU0HmrUHdUdYeXOydKSMebKihKUo+GEKF4WDpcvBsn+lHNKKrPLH8sk8v+/f3HTQbUaZ2mroHb7k+oi6L9ODyiKQ9KTagPunigLnU+KogGqgOFjlSg5j+G8p/eaQi4V1Pa2bwVi2QyH+YGpzmwiZbE69PgEptd7cU1kEUMb4qmNXbRElI/MTcsy1S0IFjrSt7dA1wRV1BSpIobzklzoe1eo=
  app: spenser-palette-picker
  on:
    repo: spenserleighton1/pallete-picker
