language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_palette_picker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: NQOUd4qXVgFvzQpu/gcoU1wEy80CnQjU7d5cF8fpIDDgwuNGG9XnKZu3eL90Lq3s+6F9976CBuC9FTCCIytPUmywXvP9EWnthK3KEig6IBdkVI8es1fj+BKiUz+YPxpCV3Ype59PdZ1g466XE3/v16Ot5y8nPkcGy+kSx7oI6rrtXs0QwucMVQ/BopQBGXpwD+JGfNgh46EvVVG0kVgbWXvV5p7tfHvqUAQXicvRuYgRy7/0nfkAYeTjib/d7U0OEuZSJ7SO2ecDIvk+Gv5pZADp0rVZ+V634z7hDhWRNiz9Dar3mocI6iTVirIJSJkUQ0WGqjBTt8tWztrqe6yta9sIzrOosc5SaHDFXqc9o1Ix6LpDyXsDLAYLae0FwH0pqb6QFoak91CmGZTl7bUfGy97UeQGTk1aNzAwr7Zr2guUe8UeVLJcsXRKp9eukeoJOblL+kLm/QVARzsgQAyYhRffytbH7l6JT3iPopGqTj6yjGm0+jMENmkqIFewSPRb9HtxKPqLn3JvcXXb7QdprC2rVgbcPIC7RTSmPtqS96Hngavmw0/f1OfJRnrADlKW4hW0Paj58BzkQKrexm6p7Ix5QPoOg4MPU6j7kK3su/aB57KMPDicniA8PswEiOVbdxg5zO8YlwYYo9RBpok3of0HX8szeKja036GUJPwcgQ=
